<h1>Pacient Survival Prediction</h1>
<hr>
<h2>Project 4</h2>
<p>This project predicts the survival of pacients in a UCI.</p>
<hr>

In [19]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import plotly.express as px
import plotly.offline as py
import plotly.graph_objs as go
import plotly.tools as tls
import plotly.figure_factory as ff

from utilerias import missing_values_table

%matplotlib inline

In [20]:
#read dataset
df_pacients = pd.read_csv('../datasets/Dataset.csv')

In [21]:
#eliminate any kind of format or upper letters on the feature's names
df_pacients.columns=df_pacients.columns.str.lower().str.replace(' ', '_')

In [22]:
df_pacients

,encounter_id,patient_id,hospital_id,hospital_death,age,bmi,elective_surgery,ethnicity,gender,height,...,aids,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,apache_3j_bodysystem,apache_2_bodysystem
0,66154,25312,118,0,68.0,22.730000,0,Caucasian,M,180.3,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Sepsis,Cardiovascular
1,114252,59342,81,0,77.0,27.420000,0,Caucasian,F,160.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Respiratory,Respiratory
2,119783,50777,118,0,25.0,31.950000,0,Caucasian,F,172.7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic
3,79267,46918,118,0,81.0,22.640000,1,Caucasian,F,165.1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular
4,92056,34377,33,0,19.0,NaN,0,Caucasian,M,188.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Trauma,Trauma
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91708,91592,78108,30,0,75.0,23.060250,0,Caucasian,M,177.8,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,Sepsis,Cardiovascular
91709,66119,13486,121,0,56.0,47.179671,0,Caucasian,F,183.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sepsis,Cardiovascular
91710,8981,58179,195,0,48.0,27.236914,0,Caucasian,M,170.2,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic
91711,33776,120598,66,0,NaN,23.297481,0,Caucasian,F,154.9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Respiratory,Respiratory
91712,1671,53612,104,0,82.0,22.031250,1,Caucasian,F,160.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Gastrointestinal,Gastrointestinal

In [15]:
df_pacients.shape

(91713, 186)

In [27]:
df_pacients.describe()

,encounter_id,patient_id,hospital_id,hospital_death,age,bmi,elective_surgery,height,icu_id,pre_icu_los_days,...,apache_4a_hospital_death_prob,apache_4a_icu_death_prob,aids,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis
count,91713.000000,91713.000000,91713.000000,91713.000000,87485.000000,88284.000000,91713.000000,90379.000000,91713.000000,91713.000000,...,83766.000000,83766.000000,90998.000000,90998.000000,90998.000000,90998.000000,90998.000000,90998.000000,90998.000000,90998.000000
mean,65606.079280,65537.131464,105.669262,0.086302,62.309516,29.185818,0.183736,169.641588,508.357692,0.835766,...,0.086787,0.043955,0.000857,0.015693,0.225192,0.012989,0.026165,0.007066,0.004132,0.020638
std,37795.088538,37811.252183,62.854406,0.280811,16.775119,8.275142,0.387271,10.795378,228.989661,2.487756,...,0.247569,0.217341,0.029265,0.124284,0.417711,0.113229,0.159628,0.083763,0.064148,0.142169
min,1.000000,1.000000,2.000000,0.000000,16.000000,14.844926,0.000000,137.200000,82.000000,-24.947222,...,-1.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,32852.000000,32830.000000,47.000000,0.000000,52.000000,23.641975,0.000000,162.500000,369.000000,0.035417,...,0.020000,0.010000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,65665.000000,65413.000000,109.000000,0.000000,65.000000,27.654655,0.000000,170.100000,504.000000,0.138889,...,0.050000,0.020000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,98342.000000,98298.000000,161.000000,0.000000,75.000000,32.930206,0.000000,177.800000,679.000000,0.409028,...,0.130000,0.060000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,131051.000000,131051.000000,204.000000,1.000000,89.000000,67.814990,1.000000,195.590000,927.000000,159.090972,...,0.990000,0.970000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [24]:
df_pacients.describe(include=['O']).T

                       count unique                   top   freq
ethnicity              90318      6             Caucasian  70684
gender                 91688      2                     M  49469
hospital_admit_source  70304     15  Emergency Department  36962
icu_admit_source       91601      5  Accident & Emergency  54060
icu_stay_type          91713      3                 admit  86183
icu_type               91713      8          Med-Surg ICU  50586
apache_3j_bodysystem   90051     11        Cardiovascular  29999
apache_2_bodysystem    90051     10        Cardiovascular  38816

In [18]:
df_pacients.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91713 entries, 0 to 91712
Data columns (total 186 columns):
 #    Column                         Non-Null Count  Dtype
---   ------                         --------------  -----
 0    encounter_id                   91713 non-null  int64
 1    patient_id                     91713 non-null  int64
 2    hospital_id                    91713 non-null  int64
 3    hospital_death                 91713 non-null  int64
 4    age                            87485 non-null  float64
 5    bmi                            88284 non-null  float64
 6    elective_surgery               91713 non-null  int64
 7    ethnicity                      90318 non-null  object
 8    gender                         91688 non-null  object
 9    height                         90379 non-null  float64
 10   hospital_admit_source          70304 non-null  object
 11   icu_admit_source               91601 non-null  object
 12   icu_id                         91713 non-null  int64
 13   icu_stay_type                  91713 non-null  object
 14   icu_type                       91713 non-null  object
 15   pre_icu_los_days               91713 non-null  float64
 16   readmission_status             91713 non-null  int64
 17   weight                         88993 non-null  float64
 18   albumin_apache                 37334 non-null  float64
 19   apache_2_diagnosis             90051 non-null  float64
 20   apache_3j_diagnosis            90612 non-null  float64
 21   apache_post_operative          91713 non-null  int64
 22   arf_apache                     90998 non-null  float64
 23   bilirubin_apache               33579 non-null  float64
 24   bun_apache                     72451 non-null  float64
 25   creatinine_apache              72860 non-null  float64
 26   fio2_apache                    20845 non-null  float64
 27   gcs_eyes_apache                89812 non-null  float64
 28   gcs_motor_apache               89812 non-null  float64
 29   gcs_unable_apache              90676 non-null  float64
 30   gcs_verbal_apache              89812 non-null  float64
 31   glucose_apache                 80677 non-null  float64
 32   heart_rate_apache              90835 non-null  float64
 33   hematocrit_apache              71835 non-null  float64
 34   intubated_apache               90998 non-null  float64
 35   map_apache                     90719 non-null  float64
 36   paco2_apache                   20845 non-null  float64
 37   paco2_for_ph_apache            20845 non-null  float64
 38   pao2_apache                    20845 non-null  float64
 39   ph_apache                      20845 non-null  float64
 40   resprate_apache                90479 non-null  float64
 41   sodium_apache                  73113 non-null  float64
 42   temp_apache                    87605 non-null  float64
 43   urineoutput_apache             42715 non-null  float64
 44   ventilated_apache              90998 non-null  float64
 45   wbc_apache                     69701 non-null  float64
 46   d1_diasbp_invasive_max         23729 non-null  float64
 47   d1_diasbp_invasive_min         23729 non-null  float64
 48   d1_diasbp_max                  91548 non-null  float64
 49   d1_diasbp_min                  91548 non-null  float64
 50   d1_diasbp_noninvasive_max      90673 non-null  float64
 51   d1_diasbp_noninvasive_min      90673 non-null  float64
 52   d1_heartrate_max               91568 non-null  float64
 53   d1_heartrate_min               91568 non-null  float64
 54   d1_mbp_invasive_max            23936 non-null  float64
 55   d1_mbp_invasive_min            23936 non-null  float64
 56   d1_mbp_max                     91493 non-null  float64
 57   d1_mbp_min                     91493 non-null  float64
 58   d1_mbp_noninvasive_max         90234 non-null  float64
 59   d1_mbp_noninvasive_min         90234 non-null  float64
 60   d1_resprate_max                91328 non-null  float64
 61   d1_resprate_min                91328 non-null  float64
 62   d1_spo2_max                    91380 non-null  float64
 63   d1_spo2_min                    91380 non-null  float64
 64   d1_sysbp_invasive_max          23754 non-null  float64
 65   d1_sysbp_invasive_min          23754 non-null  float64
 66   d1_sysbp_max                   91554 non-null  float64
 67   d1_sysbp_min                   91554 non-null  float64
 68   d1_sysbp_noninvasive_max       90686 non-null  float64
 69   d1_sysbp_noninvasive_min       90686 non-null  float64
 70   d1_temp_max                    89389 non-null  float64
 71   d1_temp_min                    89389 non-null  float64
 72   h1_diasbp_invasive_max         16785 non-null  float64
 73   h1_diasbp_invasive_min         16785 non-null  float64
 74   h1_diasbp_max                  88094 non-null  float64
 75   h1_diasbp_min                  88094 non-null  float64
 76   h1_diasbp_noninvasive_max      84363 non-null  float64
 77   h1_diasbp_noninvasive_min      84363 non-null  float64
 78   h1_heartrate_max               88923 non-null  float64
 79   h1_heartrate_min               88923 non-null  float64
 80   h1_mbp_invasive_max            16869 non-null  float64
 81   h1_mbp_invasive_min            16869 non-null  float64
 82   h1_mbp_max                     87074 non-null  float64
 83   h1_mbp_min                     87074 non-null  float64
 84   h1_mbp_noninvasive_max         82629 non-null  float64
 85   h1_mbp_noninvasive_min         82629 non-null  float64
 86   h1_resprate_max                87356 non-null  float64
 87   h1_resprate_min                87356 non-null  float64
 88   h1_spo2_max                    87528 non-null  float64
 89   h1_spo2_min                    87528 non-null  float64
 90   h1_sysbp_invasive_max          16798 non-null  float64
 91   h1_sysbp_invasive_min          16798 non-null  float64
 92   h1_sysbp_max                   88102 non-null  float64
 93   h1_sysbp_min                   88102 non-null  float64
 94   h1_sysbp_noninvasive_max       84372 non-null  float64
 95   h1_sysbp_noninvasive_min       84372 non-null  float64
 96   h1_temp_max                    69981 non-null  float64
 97   h1_temp_min                    69981 non-null  float64
 98   d1_albumin_max                 42617 non-null  float64
 99   d1_albumin_min                 42617 non-null  float64
 100  d1_bilirubin_max               38040 non-null  float64
 101  d1_bilirubin_min               38040 non-null  float64
 102  d1_bun_max                     81199 non-null  float64
 103  d1_bun_min                     81199 non-null  float64
 104  d1_calcium_max                 78644 non-null  float64
 105  d1_calcium_min                 78644 non-null  float64
 106  d1_creatinine_max              81544 non-null  float64
 107  d1_creatinine_min              81544 non-null  float64
 108  d1_glucose_max                 85906 non-null  float64
 109  d1_glucose_min                 85906 non-null  float64
 110  d1_hco3_max                    76642 non-null  float64
 111  d1_hco3_min                    76642 non-null  float64
 112  d1_hemaglobin_max              79566 non-null  float64
 113  d1_hemaglobin_min              79566 non-null  float64
 114  d1_hematocrit_max              80059 non-null  float64
 115  d1_hematocrit_min              80059 non-null  float64
 116  d1_inr_max                     33772 non-null  float64
 117  d1_inr_min                     33772 non-null  float64
 118  d1_lactate_max                 23317 non-null  float64
 119  d1_lactate_min                 23317 non-null  float64
 120  d1_platelets_max               78269 non-null  float64
 121  d1_platelets_min               78269 non-null  float64
 122  d1_potassium_max               82128 non-null  float64
 123  d1_potassium_min               82128 non-null  float64
 124  d1_sodium_max                  81518 non-null  float64
 125  d1_sodium_min                  81518 non-null  float64
 126  d1_wbc_max                     78539 non-null  float64
 127  d1_wbc_min                     78539 non-null  float64
 128  h1_albumin_max                 7889 non-null   float64
 129  h1_albumin_min                 7889 non-null   float64
 130  h1_bilirubin_max               7094 non-null   float64
 131  h1_bilirubin_min               7094 non-null   float64
 132  h1_bun_max                     16622 non-null  float64
 133  h1_bun_min                     16622 non-null  float64
 134  h1_calcium_max                 15850 non-null  float64
 135  h1_calcium_min                 15850 non-null  float64
 136  h1_creatinine_max              16756 non-null  float64
 137  h1_creatinine_min              16756 non-null  float64
 138  h1_glucose_max                 39099 non-null  float64
 139  h1_glucose_min                 39099 non-null  float64
 140  h1_hco3_max                    15619 non-null  float64
 141  h1_hco3_min                    15619 non-null  float64
 142  h1_hemaglobin_max              18590 non-null  float64
 143  h1_hemaglobin_min              18590 non-null  float64
 144  h1_hematocrit_max              18293 non-null  float64
 145  h1_hematocrit_min              18293 non-null  float64
 146  h1_inr_max                     33772 non-null  float64
 147  h1_inr_min                     33772 non-null  float64
 148  h1_lactate_max                 7344 non-null   float64
 149  h1_lactate_min                 7344 non-null   float64
 150  h1_platelets_max               16040 non-null  float64
 151  h1_platelets_min               16040 non-null  float64
 152  h1_potassium_max               19611 non-null  float64
 153  h1_potassium_min               19611 non-null  float64
 154  h1_sodium_max                  19096 non-null  float64
 155  h1_sodium_min                  19096 non-null  float64
 156  h1_wbc_max                     15760 non-null  float64
 157  h1_wbc_min                     15760 non-null  float64
 158  d1_arterial_pco2_max           32442 non-null  float64
 159  d1_arterial_pco2_min           32442 non-null  float64
 160  d1_arterial_ph_max             31590 non-null  float64
 161  d1_arterial_ph_min             31590 non-null  float64
 162  d1_arterial_po2_max            32451 non-null  float64
 163  d1_arterial_po2_min            32451 non-null  float64
 164  d1_pao2fio2ratio_max           25705 non-null  float64
 165  d1_pao2fio2ratio_min           25705 non-null  float64
 166  h1_arterial_pco2_max           15754 non-null  float64
 167  h1_arterial_pco2_min           15754 non-null  float64
 168  h1_arterial_ph_max             15289 non-null  float64
 169  h1_arterial_ph_min             15289 non-null  float64
 170  h1_arterial_po2_max            15768 non-null  float64
 171  h1_arterial_po2_min            15768 non-null  float64
 172  h1_pao2fio2ratio_max           11518 non-null  float64
 173  h1_pao2fio2ratio_min           11518 non-null  float64
 174  apache_4a_hospital_death_prob  83766 non-null  float64
 175  apache_4a_icu_death_prob       83766 non-null  float64
 176  aids                           90998 non-null  float64
 177  cirrhosis                      90998 non-null  float64
 178  diabetes_mellitus              90998 non-null  float64
 179  hepatic_failure                90998 non-null  float64
 180  immunosuppression              90998 non-null  float64
 181  leukemia                       90998 non-null  float64
 182  lymphoma                       90998 non-null  float64
 183  solid_tumor_with_metastasis    90998 non-null  float64
 184  apache_3j_bodysystem           90051 non-null  object
 185  apache_2_bodysystem            90051 non-null  object
dtypes: float64(170), int64(8), object(8)
memory usage: 130.1+ MB

/tmp/ipykernel_40678/1212657085.py:1: FutureWarning:

null_counts is deprecated. Use show_counts instead

In [23]:
#show null values
#remember de recomendation about to drop a column with more than 80% of nulls

missing_values_table(df_pacients).style.background_gradient(cmap='Blues')
#table.style.background_gradient(cmap='Blues')

Sumary :
========================================
Columns     :186
Null values :175
=========================================

In [28]:
lstFeaturesToDrop = ['encounter_id', 'hospital_admit_source', 'icu_admit_source', 'icu_id', 'icu_stay_type', 'patient_id', 'hospital_id', 'readmission_status']

In [30]:
df_pacients[lstFeaturesToDrop].isnull().sum()

encounter_id                 0
hospital_admit_source    21409
icu_admit_source           112
icu_id                       0
icu_stay_type                0
patient_id                   0
hospital_id                  0
readmission_status           0
dtype: int64

In [33]:
df_pacients[df_pacients[['bmi', 'weight', 'height']].isna().sum(axis=1) == 0]

,encounter_id,patient_id,hospital_id,hospital_death,age,bmi,elective_surgery,ethnicity,gender,height,...,aids,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,apache_3j_bodysystem,apache_2_bodysystem
0,66154,25312,118,0,68.0,22.730000,0,Caucasian,M,180.3,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Sepsis,Cardiovascular
1,114252,59342,81,0,77.0,27.420000,0,Caucasian,F,160.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Respiratory,Respiratory
2,119783,50777,118,0,25.0,31.950000,0,Caucasian,F,172.7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic
3,79267,46918,118,0,81.0,22.640000,1,Caucasian,F,165.1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular
5,33181,74489,83,0,67.0,27.560000,0,Caucasian,M,190.5,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Neurological,Neurologic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91708,91592,78108,30,0,75.0,23.060250,0,Caucasian,M,177.8,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,Sepsis,Cardiovascular
91709,66119,13486,121,0,56.0,47.179671,0,Caucasian,F,183.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sepsis,Cardiovascular
91710,8981,58179,195,0,48.0,27.236914,0,Caucasian,M,170.2,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic
91711,33776,120598,66,0,NaN,23.297481,0,Caucasian,F,154.9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Respiratory,Respiratory
91712,1671,53612,104,0,82.0,22.031250,1,Caucasian,F,160.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Gastrointestinal,Gastrointestinal